name: sql_commander
description: A SQL command chain handler and executor that is database-agnostic, with built-in support for MySQL and PostgreSQL.
version: 1.0.0
repository: https://github.com/gmpassos/sql_commander

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  intl: ^0.18.1
  logging: ^1.2.0
  mysql1: ^0.20.0
  path: ^1.8.3
  postgres: ^2.6.2
  swiss_knife: ^3.1.5

dev_dependencies:
  lints: ^2.1.1
  dependency_validator: ^3.2.2
  test: ^1.24.6
  coverage: ^1.6.3
 