name: sql_commander
description: A SQL command chain handler and executor that is database-agnostic, with built-in support for MySQL and PostgreSQL.
version: 1.1.0
repository: https://github.com/gmpassos/sql_commander

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  swiss_knife: ^3.1.6
  apollovm: ^0.0.50
  collection: ^1.18.0
  intl: ^0.19.0
  logging: ^1.2.0
  mysql1: ^0.20.0
  postgres: ^2.6.3

dev_dependencies:
  lints: ^3.0.0
  dependency_validator: ^3.2.3
  test: ^1.25.2
  coverage: ^1.7.2

#dependency_overrides:
#  apollovm:
#    path: ../apollovm_dart

